### ISSUE TITLE
Face detection doesn't work

### ISSUE THREAD

**Issue by Piero16301** [Conezi/face_camera#14]
I added the SmartFaceCamera widget in my application and the camera preview opens, but it doesn't do face detection, nor does it show a box indicating the position of the face or if the face is correctly positioned, as shown in the readme. I have cloned the example from GitHub and it does not detect it either, nor does the box show up, much less does the self-capture of the photo work.

**Comment by fiveone-digital** [comment]
Same with me

**Comment by Ayan-Qolaris** [comment]
face detection doesn't work. I am getting the following error: **PlatformException(error, Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format., null, java.lang.IllegalArgumentException: Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format.**

**Comment by ragslrp** [comment]
face detection not working as you shown in the video or in image

**Comment by Hassanmrwt** [comment]
Does not work as shown in the example preview image. Just Useless!

**Comment by lucasvps** [comment]
Anyone able to make it work?

**Comment by Conezi** [comment]
Hi guys, sorry for the delay. Thanks for using our plugin and for reporting the issue. Your feedback is invaluable in improving its quality. I'm glad to let you know that the issue has been resolved in the latest version (0.0.7). Please update your installation and feel free to reach out if you have any more questions. Thank you for your support and contribution to the face_camera plugin community.
