### ISSUE TITLE
Camera no detect in IOS issue 

### ISSUE THREAD

**Issue by devabhi7** [Conezi/face_camera#17]

**Comment by Conezi** [comment]
@devabhi7 Thanks for filing the issue. Please confirm if you followed the iOS integration process provided in the README file. Additionally, it would greatly assist in addressing your issue if you could provide a detailed description of the problem, including any error messages or unexpected behavior, along with a code sample related to the camera detection. This will allow for a more specific and targeted response to help resolve the problem.
