### ISSUE TITLE
Remove square in face detection or add a custom widget

### ISSUE THREAD

**Issue by WilliamBz12** [Conezi/face_camera#18]
I need to change the shape of square detection, could you add that?

**Comment by Conezi** [comment]
Hello there! @WilliamBz12  I wanted to let you know that I've made some updates to the plugin. Developers have more control over the square detection shape with the new features I've added. You can use the indicatorShapes and indicatorAssetImage parameters to choose the face indicator that suits your needs. Additionally, I've introduced an indicatorBuilder function which allows developers to create a custom face indicator by providing the detected face information and image size. I hope these enhancements make the plugin even more versatile for your use case. Feel free to check out the latest version and give it a try! If you have any feedback or questions, please don't hesitate to reach out.
