### ISSUE TITLE
No Camera Detected in Android

### ISSUE THREAD

**Issue by djinnsour** [Conezi/face_camera#19]
I have a timeclock app I designed using Flutterflow. I am trying to use this as a Widget to add the ability to automatically capture a photo when the employee clocks in or clocks out. I think I have added the custom code to Flutterflow correctly, and given the app Camera permissions, but I cannot seem to get the code to detect the camera. When the app starts it immediately shows "No Camera Detected". Any hints on what we might need to do to get the camera detected on Android?

// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'dart:io';
import 'package:face_camera/face_camera.dart';

class Facecamera extends StatefulWidget {
  const Facecamera({
    Key? key,
    this.width,
    this.height,
  }) : super(key: key);

  final double? width;
  final double? height;

  @override
  _FacecameraState createState() => _FacecameraState();
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await FaceCamera.initialize();

  runApp(const Facecamera());
}

class _FacecameraState extends State<Facecamera> {
  File? _capturedImage;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Photo Required for Timeclock Punch'),
          ),
          body: Builder(builder: (context) {
            if (_capturedImage != null) {
              return Center(
                child: Stack(
                  alignment: Alignment.bottomCenter,
                  children: [
                    Image.file(
                      _capturedImage!,
                      width: double.maxFinite,
                      fit: BoxFit.fitWidth,
                    ),
                    ElevatedButton(
                        onPressed: () => setState(() => _capturedImage = null),
                        child: const Text(
                          'Capture Again',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                              fontSize: 14, fontWeight: FontWeight.w700),
                        ))
                  ],
                ),
              );
            }
            return SmartFaceCamera(
                autoCapture: true,
                defaultCameraLens: CameraLens.front,
                onCapture: (File? image) {
                  setState(() => _capturedImage = image);
                },
                onFaceDetected: (Face? face) {
                  //Do something
                },
                messageBuilder: (context, face) {
                  if (face == null) {
                    return _message('Place face the camera');
                  }
                  if (!face.wellPositioned) {
                    return _message('Center your face in the square');
                  }
                  return const SizedBox.shrink();
                });
          })),
    );
  }

  Widget _message(String msg) => Padding(
        padding: const EdgeInsets.symmetric(horizontal: 55, vertical: 15),
        child: Text(msg,
            textAlign: TextAlign.center,
            style: const TextStyle(
                fontSize: 14, height: 1.5, fontWeight: FontWeight.w400)),
      );
}

**Comment by Adebayo2016** [comment]
did you do faceCamera.initialize() in your main ?

**Comment by djinnsour** [comment]
Sorry, I should have replied. I was never able to get this code working.  I
was found a different way to accomplish what I was trying to do - taking a
photo without any interaction from the user, for a timeclock app.
