### ISSUE TITLE
Face detection not working

### ISSUE THREAD

**Issue by animeshTradingswala** [Conezi/face_camera#2]
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:259)
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#google_mlkit_face_detector(31332): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MethodChannel#google_mlkit_face_detector(31332): Failed to handle method call
E/MethodChannel#google_mlkit_face_detector(31332): java.lang.IllegalArgumentException: Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format.
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:2)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.google.mlkit.vision.common.InputImage.<init>(com.google.mlkit:vision-common@@17.1.0:8)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.google.mlkit.vision.common.InputImage.fromByteArray(com.google.mlkit:vision-common@@17.1.0:2)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.google_mlkit_commons.InputImageConverter.getInputImageFromData(InputImageConverter.java:36)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.google_mlkit_face_detection.FaceDetector.handleDetection(FaceDetector.java:55)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.google_mlkit_face_detection.FaceDetector.onMethodCall(FaceDetector.java:41)
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:259)
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#google_mlkit_face_detector(31332): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#google_mlkit_face_detector(31332): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#google_mlkit_face_detector(31332): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MethodChannel#google_mlkit_face_detector(31332): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MethodChannel#google_mlkit_face_detector(31332): Failed to handle method call

This is the error which I got when I implemented the package in my application.
I'm running the application in my mobile device which is Android 12.
I'm using the latest version of the package (face_camera: ^0.0.3).

**Comment by Conezi** [comment]
@animeshTradingswala Thanks for filing the issue. Can you please share a minimal and complete code sample.

**Comment by animeshTradingswala** [comment]
import 'dart:io';

import 'package:face_camera/face_camera.dart';
import 'package:flutter/material.dart';

class MyFaceCam extends StatefulWidget {
  const MyFaceCam({Key? key}) : super(key: key);

  @override
  State<MyFaceCam> createState() => _MyFaceCamState();
}

class _MyFaceCamState extends State<MyFaceCam> {
  File? _capturedImage;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(
            title: const Text('FaceCapture example app'),
          ),
          body: Builder(builder: (context) {
            if (_capturedImage != null) {
              return Center(
                child: Stack(
                  alignment: Alignment.bottomCenter,
                  children: [
                    Image.file(
                      _capturedImage!,
                      width: double.maxFinite,
                      fit: BoxFit.fitWidth,
                    ),
                    ElevatedButton(
                        onPressed: () => setState(() => _capturedImage = null),
                        child: const Text(
                          'Capture Again',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                              fontSize: 14, fontWeight: FontWeight.w700),
                        ))
                  ],
                ),
              );
            }
            return SmartFaceCamera(
              defaultCameraLens: CameraLens.front,
              message: 'Center your face in the square',
              autoCapture: true,
              onCapture: (File? image) {
                setState(() => _capturedImage = image);
              },
            );
          })),
    );
  }
}



![photo1655124343 (1)](https://user-images.githubusercontent.com/91061153/173356932-83adc98f-9a71-4692-b4e9-33a3255b5d73.jpeg)

**Comment by Conezi** [comment]
@animeshTradingswala You just need to initialize face_camera in main.dart so it can detect your device camera. 
See example below;


void main() async{
  WidgetsFlutterBinding.ensureInitialized(); //Add this

  await FaceCamera.intialize(); //Add this

  runApp(const MyApp());
}

**Comment by animeshTradingswala** [comment]
I have already initialize face_camera in my main.dart. But still it shows me the err above.
I have just copy and paste your [that](https://pub.dev/packages/face_camera/example) code.
Can you guide me further ?

**Comment by Conezi** [comment]
Strange, what’s your minSdkVersion?

**Comment by Conezi** [comment]
Make sure to set your minSdkVersion to 21.
Also make sure you accept the permissions when prompted.
