### ISSUE TITLE
Can the capture button be disabled when no face detected?

### ISSUE THREAD

**Issue by rudyyohanes** [Conezi/face_camera#25]

**Comment by Conezi** [comment]
@rudyyohanes To clarify your question further, if you want to disable the capture button when no face is detected, you can customize the controls' visibility using the available options. You can disable the "showControls" or "showCaptureControl" features based on your requirements. If you intend to rely solely on the "autoCapture" feature and disable the manual capture button when no face is detected, adjusting these parameters can help achieve that functionality. Feel free to provide more details or specify your use case if you have additional requirements or if you need further assistance.

**Comment by Conezi** [comment]
Hi @rudyyohanes We also added `autoDisableCaptureControl` in the newly released version 0.0.9, Allowing developers to disabled capture button when no face detected.
