### ISSUE TITLE
Running the project always returns face == null

### ISSUE THREAD

**Issue by CanFor** [Conezi/face_camera#3]
Hello, thank you very much for your contribution!

I download Example and run it ,messageBuilder parameter face always returns  null

     `I/RequestThread-1( 6687): Received jpeg.
      I/RequestThread-1( 6687): Producing jpeg buffer...
      E/MethodChannel#google_mlkit_face_detector( 6687): Failed to handle method call
      E/MethodChannel#google_mlkit_face_detector( 6687): java.lang.IllegalArgumentException: Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format.
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:2)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.google.mlkit.vision.common.InputImage.<init>(com.google.mlkit:vision-common@@17.1.0:8)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.google.mlkit.vision.common.InputImage.fromByteArray(com.google.mlkit:vision-common@@17.1.0:2)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.google_mlkit_commons.InputImageConverter.getInputImageFromData(InputImageConverter.java:36)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.google_mlkit_face_detection.FaceDetector.handleDetection(FaceDetector.java:55)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.google_mlkit_face_detection.FaceDetector.onMethodCall(FaceDetector.java:41)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at android.os.Handler.handleCallback(Handler.java:873)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at android.os.Handler.dispatchMessage(Handler.java:99)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at android.os.Looper.loop(Looper.java:201)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at java.lang.reflect.Method.invoke(Native Method)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
      E/MethodChannel#google_mlkit_face_detector( 6687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
      I/flutter ( 6687): PlatformException(error, Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format., null, java.lang.IllegalArgumentException: Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format.
      I/flutter ( 6687): 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:2)
      I/flutter ( 6687): 	at com.google.mlkit.vision.common.InputImage.<init>(com.google.mlkit:vision-common@@17.1.0:8)
      I/flutter ( 6687): 	at com.google.mlkit.vision.common.InputImage.fromByteArray(com.google.mlkit:vision-common@@17.1.0:2)
      I/flutter ( 6687): 	at com.google_mlkit_commons.InputImageConverter.getInputImageFromData(InputImageConverter.java:36)
      I/flutter ( 6687): 	at com.google_mlkit_face_detection.FaceDetector.handleDetection(FaceDetector.java:55)
      I/flutter ( 6687): 	at com.google_mlkit_face_detection.FaceDetector.onMethodCall(FaceDetector.java:41)
      I/flutter ( 6687): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
      I/flutter ( 6687): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
      I/flutter ( 6687): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
      I/flutter ( 6687): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
      I/flutter ( 6687): 	at android.os.Handler.handleCallback(Handler.java:873)
      I/flutter ( 6687): 	at android.os.Handler.dispatchMessage(Handler.java:99)
      I/flutter ( 6687): 	at android.os.Looper.loop(Looper.java:201)
      I/flutter ( 6687): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
      I/flutter ( 6687): 	at java.lang.reflect.Method.invoke(Native Method)
      I/flutter ( 6687): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
      I/flutter ( 6687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
      I/flutter ( 6687): )`

Android 9

[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by Conezi** [comment]
@CanFor Thanks for filing the issue. If messageBuilder parameter face returns null, It simply meant that the camera did not detect any face. You can try choosing a higher ImageResolution, a different CameraLens or try testing on another device.
