### ISSUE TITLE
Unable to stop SmartFaceCamera when transitioning to a new screen

### ISSUE THREAD

**Issue by MaxwellEdisons** [Conezi/face_camera#36]
Body:
Hello,

I'm encountering an issue with the SmartFaceCamera plugin. When I transition to a new screen in my app from the screen using the plugin, the camera continues to run. I haven't found a way to stop the camera when switching screens after going through the plugin's documentation and source code.

This issue is resulting in the camera continuing to run and consuming resources after navigation. I would like a way to stop the camera when transitioning pages, similar to how it stops when the app is exited or when the back navigation is used.

Is there a way to stop the camera during a screen transition that I might be missing? Or would you consider a future update to the plugin to allow developers to stop the camera when switching screens?

Thank you for developing this great plugin!

**Comment by igbokwenu** [comment]
This will be a good feature to have. A way to disable the camera when not in use. I am having a similar challenge.

**Comment by Conezi** [comment]
We have added a controller to the SmartFaceCamera, enabling you to call functions such as stopImageStream. This should help you stop the camera when transitioning to a new screen. Please update to the latest version and try again. Thank you!
