### ISSUE TITLE
New release 0.1.1 not working

### ISSUE THREAD

**Issue by tanpham380** [Conezi/face_camera#44]
Hello @Conezi,
I have using new version 0.1.1 on my app it can not send to google_mlkit_face_detection 0.11.0, So I have debug and See problem In packages Camera 0.11.0 it can not set default nv21 format for andoird device(it return yuv420 format),  problem in https://github.com/flutter/flutter/issues/145961 /
Problem can resolve with ways
1) Downgrade Packages Camera 0.11.0 to camera: ^0.10.6
2)  convert yuv420_888 to nv21 manually:
Example in Java code:
extension Nv21Converter on CameraImage {
  Uint8List getNv21Uint8List() {
    final width = this.width;
    final height = this.height;

    final yPlane = planes[0];
    final uPlane = planes[1];
    final vPlane = planes[2];

    final yBuffer = yPlane.bytes;
    final uBuffer = uPlane.bytes;
    final vBuffer = vPlane.bytes;

    final numPixels = (width * height * 1.5).toInt();
    final nv21 = List<int>.filled(numPixels, 0);

    // Full size Y channel and quarter size U+V channels.
    int idY = 0;
    int idUV = width * height;
    final uvWidth = width ~/ 2;
    final uvHeight = height ~/ 2;
    // Copy Y & UV channel.
    // NV21 format is expected to have YYYYVU packaging.
    // The U/V planes are guaranteed to have the same row stride and pixel stride.
    // getRowStride analogue??
    final uvRowStride = uPlane.bytesPerRow;
    // getPixelStride analogue
    final uvPixelStride = uPlane.bytesPerPixel ?? 0;
    final yRowStride = yPlane.bytesPerRow;
    final yPixelStride = yPlane.bytesPerPixel ?? 0;

    for (int y = 0; y < height; ++y) {
      final uvOffset = y * uvRowStride;
      final yOffset = y * yRowStride;

      for (int x = 0; x < width; ++x) {
        nv21[idY++] = yBuffer[yOffset + x * yPixelStride];

        if (y < uvHeight && x < uvWidth) {
          final bufferIndex = uvOffset + (x * uvPixelStride);
          //V channel
          nv21[idUV++] = vBuffer[bufferIndex];
          //V channel
          nv21[idUV++] = uBuffer[bufferIndex];
        }
      }
    }
    return Uint8List.fromList(nv21);
  }
}

**Comment by Conezi** [comment]
@tanpham380 Thanks for filing the issue. The plugin is designed to work even with the yuv420 format, so it should not be causing issues with the Google ML Kit face detection. If the error persists, please provide the details of the device you're using, such as the model and Android version, so we can further investigate and find a solution.

**Comment by Conezi** [comment]
@tanpham380 Thank you for bringing this issue to our attention and for your detailed debugging efforts. We are pleased to inform you that the problem with the default NV21 format on Android devices has been resolved in version 0.1.2, thanks to your valuable input. We appreciate your support.

**Comment by tanpham380** [comment]
Ok, I will close issues now
thanks @Conezi
