### ISSUE TITLE
Can we detect how many people in camera?

### ISSUE THREAD

**Issue by andikatp** [Conezi/face_camera#46]
Hi, im a newbie and i'm working on an attendance app. I just wanna know can we detect how many people inside the photo? right now i use google ml kit like this, so i can count how many people there like this:

` final List<Face> faces = await faceDetector.processImage(inputImage);`

Can I do something similar to directly count people? I just need to tell users if there's more than one person detected.

Thanks!

**Comment by tanpham380** [comment]
![image](https://github.com/Conezi/face_camera/assets/74082201/5f338094-4c3a-4eee-b108-fa0ffd88bc18)
You can see here func will get face on face_camera plugin
If want u can inheritance this class for custom what you want. 
this Plugin just implement google ml face detect like 
![image](https://github.com/Conezi/face_camera/assets/74082201/8788d4ce-42da-44ab-b12d-4b34c3fb27a4)

**Comment by andikatp** [comment]
thanks tanpham
