### ISSUE TITLE
Face detection not working

### ISSUE THREAD

**Issue by muzammil-git** [Conezi/face_camera#49]
I switched from 0.0.9 to 0.1.1, it doesn't capture face landmarks.

**Comment by Conezi** [comment]
@muzammil-git The issue with capturing face landmarks that you encountered after switching from version 0.0.9 to 0.1.1 has been resolved in version 0.1.2. Please update to the latest version and verify if the problem persists. If you continue to experience the same error, feel free to reopen the issue for further assistance.

**Comment by muzammil-git** [comment]
Thanks @Conezi, I will check it up.
