### ISSUE TITLE
Updating readme for detailed method usage for controller?

### ISSUE THREAD

**Issue by teddy-harfa** [Conezi/face_camera#53]
Hi! 
First, I want to say thanks for the plugin, really appreciate how customizable the plugin.
Anyway, can you update the readme for detailed method you can use for the controller (like changing flash, taking photo, stopping, etc)? For now I want to change the flash using custom widget outside the face_camera, but kinda confused for how to and what state right now to change the flash icon.
Thanks!

**Comment by Conezi** [comment]
@teddy-harfa Thanks for filing the issue. You can achieve what you want with the `flashControlBuilder` as described in the readme. Below is an example code.

```dart
SmartFaceCamera(
                controller: controller,
                flashControlBuilder: (context, mode){
                  if(mode == CameraFlashMode.always){
                    //Flash is on. Return an icon
                  }
                  if(mode == CameraFlashMode.auto){
                    //Flash is in automatic mode. Return an icon
                  }
                  if(mode == CameraFlashMode.off){
                    //Flash is off. Return an icon
                  }
                },);
```
