### ISSUE TITLE
cannt work on xiaomi;

### ISSUE THREAD

**Issue by VonZen** [Conezi/face_camera#6]
`_controller = CameraController(cameras.first,
          EnumHandler.imageResolutionToResolutionPreset(widget.imageResolution),
          enableAudio: widget.enableAudio,
          imageFormatGroup: ImageFormatGroup.jpeg);`
it should remove ' imageFormatGroup: ImageFormatGroup.jpeg', or cannt detect face in android;

plz check out demo:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example.

it work fine in my device;

device: xiaomi Mix 2s;

**Comment by popopopdcvvbf** [comment]
去掉之前几个手机都不行，去掉之后MIX3还是不行，这问题真头疼

**Comment by Conezi** [comment]
Hi guys, sorry for the delay. Thanks for using our plugin and for reporting the issue. Your feedback is invaluable in improving its quality. I'm glad to let you know that the issue has been resolved in the latest version (0.0.7). Please update your installation and feel free to reach out if you have any more questions. Thank you for your support and contribution to the face_camera plugin community.
