### ISSUE TITLE
Getting Image failed

### ISSUE THREAD

**Issue by eansharma** [Conezi/face_camera#64]
java.lang.IllegalArgumentException
I/flutter ( 3677): PlatformException(InputImageConverterError, java.lang.IllegalArgumentException, null, null)
I/e.faeautucamera( 3677): Background concurrent mark compact GC freed 4187(500KB) AllocSpace objects, 26(7832KB) LOS objects, 58% free, 4271KB/10MB, paused 153us,5.551ms total 54.803ms

**Comment by AyushUlric** [comment]
same issue, any updates?

**Comment by GeorgeGoAy** [comment]
same issue on Poco F4 

Getting Image failed
E/ImageError(26501): java.lang.IllegalArgumentException
I/flutter (26501): PlatformException(InputImageConverterError, java.lang.IllegalArgumentException, null, null)

**Comment by sha3rawi33** [comment]
same issue

**Comment by azureem** [comment]
: Getting Image failed
E/ImageError( 5754): java.lang.IllegalArgumentException
I/flutter ( 5754): PlatformException(InputImageConverterError, java.lang.IllegalArgumentException, null, null) is there any solution?

**Comment by mougangfrank** [comment]
**Getting Image failed**
**E/ImageError( 5754): java.lang.IllegalArgumentException
I/flutter ( 5754): PlatformException(InputImageConverterError, java.lang.IllegalArgumentException, null, null) is there any solution?**

**Comment by Conezi** [comment]
This issue has been resolved in version 0.1.3. Please update to the latest version and verify if the problem persists. If you continue to experience the same error, feel free to reopen the issue for further assistance.

**Comment by mougangfrank** [comment]
Thank you
Please, I have a preoccupation. How can I use face_camera to implement
example like a preview who's inside pub.dev

Le jeu. 24 oct. 2024 à 15:07, Collins Eneze ***@***.***> a
écrit :
