### ISSUE TITLE
Getting Image failed only on VIVO S16

### ISSUE THREAD

**Issue by CitienTZ** [Conezi/face_camera#65]
Auto captured a broken picture on Vivo S16. Cause I don't own such a phone , there's no debuging info.Anyone else ever met such problem?
![812b4a29417ee7eb4d79e0b9e7f014d](https://github.com/user-attachments/assets/9580b8e4-20fe-4913-bd5d-e58ce9be4b5f)

**Comment by Conezi** [comment]
This issue has been resolved in version 0.1.3. Please update to the latest version and verify if the problem persists. If you continue to experience the same error, feel free to reopen the issue for further assistance.
