### ISSUE TITLE
Upgrade AGP Version

### ISSUE THREAD

**Issue by TuleSimon** [Conezi/face_camera#66]
If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by hasnainelahi** [comment]
same issue here

**Comment by Amr-Samy** [comment]
![image](https://github.com/user-attachments/assets/69c55f13-0e9b-4ddd-aa71-ae43935007b4)

**Comment by yopuej** [comment]
Has anyone managed to resolve this issue?

**Comment by Amr-Samy** [comment]
@yopuej A co worker did by upgrading every thing to latest ( gradle , JDK , Flutter , android studio ) 
open file
../.pub-cache/hosted/pub.dev/face_camera-0.1.3/android/build.gradle
```
android {
   namespace 'com.conezi.face_camera'
}
```
or wait for the new version

**Comment by Code-changed** [comment]
Conezi can you add this in android build.gradle android {
   namespace 'com.conezi.face_camera'
} ?

**Comment by Conezi** [comment]
This issue has been resolved in version 0.1.4. Please update to the latest version and verify if the problem persists. If you continue to experience the same error, feel free to reopen the issue for further assistance.
