### ISSUE TITLE
Face detection 

### ISSUE THREAD

**Issue by azureem** [Conezi/face_camera#68]
Face detection is not working, what can be a reason for that?

**Comment by 0xkenn** [comment]
same here

**Comment by Amr-Samy** [comment]
Same too , It was working fine few days ago , did any one figured it out ?

**Comment by Conezi** [comment]
This issue has been resolved in version 0.1.3. Please update to the latest version and verify if the problem persists. If you continue to experience the same error, feel free to reopen the issue for further assistance.
