### ISSUE TITLE
IOS pod installation failing due to dependency conflict

### ISSUE THREAD

**Issue by gihan667** [Conezi/face_camera#69]
Pod installation failing with the below error when used with `cloud_firestore 5.4.4` 

```
CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 5.4.0, which depends on
      Firebase/Firestore (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseFirestore (~> 11.0.0) was resolved to 11.0.0, which depends on
          FirebaseFirestoreInternal (= 11.0.0) was resolved to 11.0.0, which depends on
            nanopb (~> 3.30910.0)

    google_mlkit_face_detection (from `.symlinks/plugins/google_mlkit_face_detection/ios`) was resolved to 0.11.0, which depends on
      GoogleMLKit/FaceDetection (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)
```

Fixed with overriding the `google_mlkit_face_detection` dependency in `pubspec.yml` with latest version as follows,

```
dependency_overrides:
  google_mlkit_face_detection: 0.12.0
```

I'm further testing with this fix, I will post here If there any issue with this. Meanwhile please update the `google_mlkit_face_detection` dependency version in package to latest.

**Comment by LeonardoMaito** [comment]
I'm having a similar issue when running `firebase_messaging: ^15.1.3` and `firebase_core: ^3.6.0`.

firebase_messaging depends on GoogleDataTransport (~> 10.0).

google_mlkit_face_detection depends on GoogleDataTransport (< 10.0, >= 9.4.1).

It seems to be necessary to update google_mlkit_face_detection to the latest version.
